services:
  - type: web
    name: interview-prep-hub-api
    env: node
    buildCommand: ./build.sh
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: mongodb
          property: connectionString
    plan: free
